version: '2'
services:
  web:
    image: nginx:1.11-alpine
    links:
      - phpfpm
    ports:
      - "8080:80"
    volumes:
    #The nginx configuration file is hosted outside of the container for easy altering and keeping the container
    #stateless. It is hosted in the nginx folder.
      - ../nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    #The access.log and error.log files are hosted outside of the container for easy access. It is hosted in the
    #nginx/log folder.
      - ../nginx/log:/var/log/nginx
    volumes_from:
      - phpfpm
  phpfpm:
    build: php-7.0-fpm-custom
    environment:
    #Here environment variables can be set which can be retrieved by $_SERVER
      - ENVIRONMENT=DEVELOPMENT
    links:
      - db
    volumes:
    #The webfiles are stored in the wwwroot folder outside of the container for easy altering and keeping the container
    #stateless.
      - ../wwwroot:/var/www/html
    #The php configuration file (php.ini) is hosted outside of the container for easy altering and keeping the container
    #stateless. It is hosted in the php folder.
      - ../php/php.ini:/usr/local/etc/php/php.ini
    #The error.log files for php are hosted outside of the container for easy access. It is hosted in the
    #php/log folder.
      - ../php/log/php_errors.log:/var/log/php_errors.log
    ports:
      - "9000:9000"
  db:
    image: mariadb:10.1
    environment:
      - MYSQL_ROOT_PASSWORD=mypassword
    volumes:
    #The database is stored in the mysql folder outside of the container to keep the container stateless.
      - ../mysql:/var/lib/mysql
    #The MariaDB configuration file (my.cnf) is hosted outside of the container for easy altering and keeping the
    #container stateless. It is hosted in the etc/mysql folder.
      - ../etc/mysql/my.cnf:/etc/mysql/my.cnf
    ports:
      - "3306:3306"
