version: '2'
services:
  web:
    image: nginx:1.11-alpine
    links:
      - phpfpm
    ports:
      - "8080:80"
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ../nginx/log:/var/log/nginx
    volumes_from:
      - phpfpm
  phpfpm:
    build: php-7.0-fpm-custom
    environment:
      - ENVIRONMENT=DEVELOPMENT
    links:
      - db
    volumes:
      - ../wwwroot:/var/www/html
      - ../php/php.ini:/usr/local/etc/php/php.ini
      - ../php/log/php_errors.log:/var/log/php_errors.log
    ports:
      - "9000:9000"
  db:
    image: mariadb:10.1
    environment:
      - MYSQL_ROOT_PASSWORD=mypassword
    volumes:
      - ../mysql:/var/lib/mysql
      - ../etc/mysql/my.cnf:/etc/mysql/my.cnf
    ports:
      - "3306:3306"
